/**
 * playerStatsTypes.ts — Types and loader for pre-computed player stats
 *
 * Data comes from player-stats.json, generated by enrich-players.js
 * Used by: sidebar alerts, ranking, filters, comparação
 */

export interface PlayerStats {
  lastRoundDate: string | null;
  daysSinceLastRound: number | null;
  roundsTotal: number;
  roundsLast3m: number;
  roundsLast6m: number;
  roundsLast12m: number;
  avgSD5: number | null;
  avgSD8: number | null;     // best 8 of last 20 — "power ranking" metric
  avgSD20: number | null;
  lastSD: number | null;
  currentHcp: number | null;
  hcpTrend: "up" | "stable" | "down";  // up = improving (HCP ↓)
  hcpDelta3m: number | null;
  formAlert: "hot" | "cold" | null;
  bestGross: number | null;
  avgGross5: number | null;
  avgGross20: number | null;
}

export type PlayerStatsDb = Record<string, PlayerStats>;

let _cache: PlayerStatsDb | null = null;

export async function loadPlayerStats(): Promise<PlayerStatsDb> {
  if (_cache) return _cache;
  try {
    const resp = await fetch("/player-stats.json");
    if (!resp.ok) {
      console.warn("player-stats.json not found — sidebar enhancements disabled");
      return {};
    }
    let text = await resp.text();
    if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
    _cache = JSON.parse(text) as PlayerStatsDb;
    return _cache;
  } catch (e) {
    console.warn("Failed to load player-stats.json:", e);
    return {};
  }
}
